apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap
data:
  mongo.host: my-release-mongodb
  mongo.db: acteurs
  mon.service.url: http://mon-service:80
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: <Password>
