# Trigger: Quand je push sur la branche "main"
on:
  push:
    branches:
      - main
#   pull_request:
#     branches: 
#       - main
#   schedule:
#     - cron: 00 09 * * *

jobs:
  demo:
    name: Demonstration d'une CI avec GithubAction
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - name: Récupération du code
        uses: actions/checkout@v3.5.2
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: gradlew test
   
