# Trigger: Quand je push sur la branche "main"
on:
  push:
    branches:
      - main
#   pull_request:
#     branches: 
#       - main
#   schedule:
#     - cron: 00 09 * * *

jobs:
  demo:
    name: Demonstration d'une CI avec GithubAction
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - run: ls -a
      - name: Récupération du code
        uses: actions/checkout@v3.5.2
      - run: ls -a
   
