# Trigger: Quand je push sur la branche "main"
on:
  push:
    branches:
      - main
#   pull_request:
#     branches: 
#       - main
#   schedule:
#     - cron: 00 09 * * *

jobs:
  demo:
    name: Demonstration d'une CI avec GithubAction
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - name: Récupération du code
        uses: actions/checkout@v3.5.2
      - run: chmod -x gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        run: sh gradlew
